dist: xenial
language: ruby
rvm:
- 2.5.7
- 2.6.5
sudo: false
cache:
  bundler: true
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
  - PARALLEL_TEST_PROCESSORS=2
  matrix:
  - TEST_SUITE=vmdb PARALLEL=true
  - TEST_SUITE=brakeman
matrix:
  fast_finish: true
script:
- egrep '^flags.*(vmx|svm)' /proc/cpuinfo
