source 'https://rubygems.org'

# Specify your gem's dependencies in manageiq-gems-pending.gemspec
gemspec

# Modified gems (forked on github)
gem "handsoap", "~>0.2.5", :require => false, :git => "git://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-4"
gem "rubywbem",            :require => false, :git => "git://github.com/ManageIQ/rubywbem.git", :branch => "rubywbem_0_1_0"

group :appliance do
  gem "highline", "~> 1.6.21", :require => false  # Needed for the appliance_console
end

# Linux-only section
if RbConfig::CONFIG["host_os"].include?("linux")
  gem "linux_block_device", ">=0.1.0", :require => false

  if RbConfig::CONFIG["host_cpu"] == "x86"  # 32 bit Linux.
    gem "large_file_linux", "~>0.1.0", :require => false
  end
end

# Windows only. Do not put in Gemfile.lock on other platforms.
if Gem.win_platform?
  gem "win32-process", "~>0.8.0", :require => false, :platforms => [:mswin, :mingw]
end
