require 'bundler/gem_tasks'

Dir["lib/tasks/**/*.rake"].sort.each { |ext| load ext }

task :default do
  Rake::Task["spec"].invoke
  Rake::Task["test"].invoke
  if ENV["TRAVIS"]
    require 'coveralls/rake/task'
    Coveralls::RakeTask.new
    Rake::Task["coveralls:push"].invoke
  end
end
